/**
 * Comprehensive Synthetic Well Fixtures for Indian Petroleum Basins.
 *
 * NOTE: All coordinates and incident logs are FICTIONAL / SYNTHETIC DEMO data
 * designed to demonstrate multi-basin lookahead, offset correlation, and
 * geospatial hazard mapping across India's primary hydrocarbon provinces.
 *
 * Provenance: Synthetic Fixture (WGS 84 / EPSG:4326).
 */

export type BasinKey =
  | "all"
  | "upper_assam"
  | "rajasthan"
  | "cambay"
  | "mumbai_offshore"
  | "krishna_godavari"
  | "cauvery";

export type SyntheticBasinWell = {
  id: string;
  well_id: string;
  name: string;
  field_name: string;
  basin: string;
  basin_key: Exclude<BasinKey, "all">;
  state: string;
  latitude: number;
  longitude: number;
  data_kind: "synthetic";
  operator: string;
  target_formation: string;
  depth_m: number;
  primary_hazard: string;
  event_type: "mud_loss" | "kick" | "stuck_pipe" | "tight_hole" | "abnormal_pressure" | "none";
  event_count: number;
  incident_summary: string;
  lithology: string;
  spud_year: number;
  is_active?: boolean;
};

export type BasinInfo = {
  key: Exclude<BasinKey, "all">;
  name: string;
  state: string;
  center: [number, number]; // [lat, lng]
  zoom: number;
  geological_setting: string;
  primary_play: string;
};

export const BASIN_REGISTRY: Record<Exclude<BasinKey, "all">, BasinInfo> = {
  upper_assam: {
    key: "upper_assam",
    name: "Upper Assam",
    state: "Assam & Arunachal Pradesh",
    center: [27.25, 95.15],
    zoom: 9,
    geological_setting: "Foreland Assam-Arakan Basin with complex thrust faulting",
    primary_play: "Barail & Tipam Sandstones, Kopili splintery shales",
  },
  rajasthan: {
    key: "rajasthan",
    name: "Rajasthan (Barmer)",
    state: "Rajasthan",
    center: [25.85, 71.28],
    zoom: 9,
    geological_setting: "Tertiary rift basin with high-permeability fluvial sands",
    primary_play: "Fatehgarh Sandstone & Dharvi Dungar Formation",
  },
  cambay: {
    key: "cambay",
    name: "Cambay",
    state: "Gujarat",
    center: [22.2, 72.7],
    zoom: 9,
    geological_setting: "Intra-cratonic rift graben with overpressured shale sequences",
    primary_play: "Hazad Sandstone, Kalol Member & Cambay Shale",
  },
  mumbai_offshore: {
    key: "mumbai_offshore",
    name: "Mumbai Offshore",
    state: "Western Continental Shelf",
    center: [19.25, 71.65],
    zoom: 8,
    geological_setting: "Passive continental margin with major carbonate bank deposits",
    primary_play: "L-III Miocene Limestone & Bassein Carbonates",
  },
  krishna_godavari: {
    key: "krishna_godavari",
    name: "Krishna-Godavari",
    state: "Andhra Pradesh & KG Offshore",
    center: [16.45, 82.15],
    zoom: 9,
    geological_setting: "Poly-history rift to passive margin deltaic turbidite system",
    primary_play: "Ravva Sandstone & Pliocene deepwater channel sands",
  },
  cauvery: {
    key: "cauvery",
    name: "Cauvery",
    state: "Tamil Nadu & Palk Bay",
    center: [10.8, 79.7],
    zoom: 9,
    geological_setting: "Mesozoic-Cenozoic rifted basin with deep graben clastics",
    primary_play: "Kamalapuram Formation & Bhuvanagiri Sandstones",
  },
};

export const ALL_SYNTHETIC_WELLS: SyntheticBasinWell[] = [
  /* ═══════════════════════════════════════════════════════════════
     1. UPPER ASSAM BASIN (10 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "fb6ffe02-314d-52df-93f3-6ef7afb989f9",
    well_id: "SYN-A-MAIN",
    name: "SYN-A (Active Replay)",
    field_name: "Nahorkatiya Extended",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.0000,
    longitude: 95.0000,
    data_kind: "synthetic",
    operator: "Oil India Limited (Synthetic Ref)",
    target_formation: "Tipam / Barail Sandstone",
    depth_m: 2500,
    primary_hazard: "Mud Loss in Tipam thief zone",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Live lookahead monitoring: active target interval at 2,000–2,300 m with projected 2,030 m loss corridor.",
    lithology: "Massive deltaic sandstones with interbedded siltstones",
    spud_year: 2024,
    is_active: true,
  },
  {
    id: "cab695d8-9935-588d-aad2-1d69772bd5a0",
    well_id: "SYN-B-MAIN",
    name: "SYN-B (Offset Hazard)",
    field_name: "Nahorkatiya North",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.0000,
    longitude: 95.0100,
    data_kind: "synthetic",
    operator: "Oil India Limited (Synthetic Ref)",
    target_formation: "SYN-F1 Sandstone",
    depth_m: 2500,
    primary_hazard: "Severe mud losses (1,930–1,940 m MD)",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Recorded 6 hours NPT during sudden lost circulation at 1,930 m MD. Golden demo analogue source.",
    lithology: "Coarse porous sandstones with fractured transition",
    spud_year: 2023,
  },
  {
    id: "b4fb457a-2525-57a0-95a4-51694c2cd366",
    well_id: "SYN-C-MAIN",
    name: "SYN-C (Lithology Offset)",
    field_name: "Nahorkatiya North",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.0000,
    longitude: 95.0200,
    data_kind: "synthetic",
    operator: "Oil India Limited (Synthetic Ref)",
    target_formation: "SYN-F2 Formation",
    depth_m: 2500,
    primary_hazard: "Formation mismatch baseline",
    event_type: "none",
    event_count: 0,
    incident_summary: "Calibrated negative analogue with different geological formation code.",
    lithology: "Fine laminated siltstone and claystones",
    spud_year: 2023,
  },
  {
    id: "1864bd67-714d-5859-b989-7a4d60d8bc4d",
    well_id: "SYN-D-MAIN",
    name: "SYN-D (Distant Offset)",
    field_name: "Moran Sector",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.0000,
    longitude: 95.2000,
    data_kind: "synthetic",
    operator: "Oil India Limited (Synthetic Ref)",
    target_formation: "SYN-F1 Sandstone",
    depth_m: 2500,
    primary_hazard: "Outside 5 km radius boundary",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Demonstrates spatial exclusion filtering when radius is restricted to 5 km.",
    lithology: "Delta plain fluvial sandstones",
    spud_year: 2022,
  },
  {
    id: "synth-nhk-302",
    well_id: "NHK-302-MAIN",
    name: "Nahorkatiya NHK-302",
    field_name: "Nahorkatiya Central",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.2850,
    longitude: 95.3450,
    data_kind: "synthetic",
    operator: "Oil India Limited",
    target_formation: "Kopili / Sylhet Limestone",
    depth_m: 3650,
    primary_hazard: "Severe mud loss (45 bbl/hr) & Kopili stuck pipe",
    event_type: "stuck_pipe",
    event_count: 2,
    incident_summary: "Mud losses in Tipam at 2,145 m; differential sticking in sloughing Kopili shales at 3,482 m MD. Jarred free.",
    lithology: "Massive Tipam Sandstone overlying Kopili splintery calcareous shales",
    spud_year: 2024,
  },
  {
    id: "synth-mor-045",
    well_id: "MOR-045-MAIN",
    name: "Moran MOR-045",
    field_name: "Moran Field",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.1950,
    longitude: 94.9250,
    data_kind: "synthetic",
    operator: "Oil India Limited",
    target_formation: "Barail Coal / Sandstone",
    depth_m: 3920,
    primary_hazard: "Barail gas kick (18 bbl pit gain)",
    event_type: "kick",
    event_count: 2,
    incident_summary: "Encountered 62 bbl mud loss in Upper Tipam at 2,030 m; sharp gas influx at 2,985 m killed with 1.26 SG mud.",
    lithology: "Cyclic sandstone-shale-coal sequence of Barail Group",
    spud_year: 2023,
  },
  {
    id: "synth-dgb-108",
    well_id: "DGB-108-MAIN",
    name: "Digboi DGB-108",
    field_name: "Digboi Historic Anticline",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.3820,
    longitude: 95.6280,
    data_kind: "synthetic",
    operator: "Oil India Limited",
    target_formation: "Tipam Sandstone",
    depth_m: 2450,
    primary_hazard: "Steep dip hole deviation and tight spots",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Drilled on steep asymmetric anticline flank; frequent reaming required through Tipam conglomerates.",
    lithology: "Coarse-grained pebbly sandstones and ferruginous shales",
    spud_year: 2021,
  },
  {
    id: "synth-bgj-015",
    well_id: "BGJ-015-MAIN",
    name: "Baghjan BGJ-015",
    field_name: "Baghjan High Pressure Gas",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.5850,
    longitude: 95.3950,
    data_kind: "synthetic",
    operator: "Oil India Limited",
    target_formation: "Barail Main Gas Sand",
    depth_m: 3880,
    primary_hazard: "High pore pressure & fractured sand mud loss",
    event_type: "abnormal_pressure",
    event_count: 2,
    incident_summary: "High pressure gas sand at 3,710 m requiring 1.35 SG synthetic oil-based mud with managed pressure drilling.",
    lithology: "Fine clean quartz arenite sands capped by thick marine Girujan clays",
    spud_year: 2022,
  },
  {
    id: "synth-ksj-004",
    well_id: "KSJ-004-MAIN",
    name: "Kusijan KSJ-004",
    field_name: "Kusijan Development",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 27.5250,
    longitude: 95.5450,
    data_kind: "synthetic",
    operator: "Oil India Limited",
    target_formation: "Lower Tipam Sandstone",
    depth_m: 3550,
    primary_hazard: "Pack-off during tripping in Girujan",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Reactive smectite swelling in Girujan claystone caused swab/surge spikes and pack-off risk.",
    lithology: "Variegated mottling clays and river channel sands",
    spud_year: 2023,
  },
  {
    id: "synth-bor-007",
    well_id: "BOR-007-MAIN",
    name: "Borholla BOR-007",
    field_name: "Borholla Shelf Edge",
    basin: "Upper Assam",
    basin_key: "upper_assam",
    state: "Assam",
    latitude: 26.3150,
    longitude: 93.9120,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Sylhet Limestone & Basement",
    depth_m: 3100,
    primary_hazard: "Severe cavernous limestone mud loss",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Total losses of 120 bbl/hr in vuggy Sylhet limestone; cured with diesel-bentonite-cement (DBC) plug.",
    lithology: "Fossiliferous foraminiferal biomicrite limestone",
    spud_year: 2020,
  },

  /* ═══════════════════════════════════════════════════════════════
     2. RAJASTHAN (BARMER & JAISALMER) BASIN (6 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "synth-mgl-01",
    well_id: "MGL-01-MAIN",
    name: "Mangala MGL-01",
    field_name: "Mangala Field",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 25.8150,
    longitude: 71.2400,
    data_kind: "synthetic",
    operator: "Cairn Oil & Gas (Synthetic Ref)",
    target_formation: "Fatehgarh Sandstone",
    depth_m: 1850,
    primary_hazard: "Loss of circulation in coarse braided sand",
    event_type: "mud_loss",
    event_count: 2,
    incident_summary: "High permeability Darcy-range Fatehgarh sands caused 55 bbl/hr seepage losses. Sealed with fine calcium carbonate.",
    lithology: "Stacked braided fluvial channel sands with waxy crude saturation",
    spud_year: 2022,
  },
  {
    id: "synth-bhy-04",
    well_id: "BHY-04-MAIN",
    name: "Bhagyam BHY-04",
    field_name: "Bhagyam Field",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 26.0420,
    longitude: 71.3120,
    data_kind: "synthetic",
    operator: "Cairn Oil & Gas (Synthetic Ref)",
    target_formation: "Barmer Hill & Fatehgarh",
    depth_m: 1620,
    primary_hazard: "Tight hole in low-permeability diatomite",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "High overbalance in micro-porous Barmer Hill diatomaceous porcellanite caused differential drag during connections.",
    lithology: "Siliceous shale and diatomaceous porcellanite",
    spud_year: 2021,
  },
  {
    id: "synth-ash-02",
    well_id: "ASH-02-MAIN",
    name: "Aishwarya ASH-02",
    field_name: "Aishwarya Field",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 25.8750,
    longitude: 71.2180,
    data_kind: "synthetic",
    operator: "Cairn Oil & Gas (Synthetic Ref)",
    target_formation: "Fatehgarh Sandstone FM-1",
    depth_m: 1940,
    primary_hazard: "Shallow aquifer flow check & mud loss",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Thief zone encountered at 1,420 m MD in Fatehgarh Member 2; loss rate 38 bbl/hr stabilized with fibrous LCM.",
    lithology: "Medium-grained sub-arkosic quartzose sandstone",
    spud_year: 2023,
  },
  {
    id: "synth-rag-07",
    well_id: "RAG-07-MAIN",
    name: "Raageshwari RAG-07",
    field_name: "Raageshwari Deep Gas",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 25.6200,
    longitude: 71.4350,
    data_kind: "synthetic",
    operator: "Cairn Oil & Gas (Synthetic Ref)",
    target_formation: "Malani Rhyolite Volcanics",
    depth_m: 3200,
    primary_hazard: "Gas kick in tight fractured volcanics",
    event_type: "kick",
    event_count: 2,
    incident_summary: "High-pressure gas influx at 2,980 m MD upon intersecting volcanic fracture system. SIDPP reached 620 psi.",
    lithology: "Highly fractured felsic rhyolites and welded pyroclastic tuffs",
    spud_year: 2022,
  },
  {
    id: "synth-tuk-03",
    well_id: "TUK-03-MAIN",
    name: "Tukaram TUK-03",
    field_name: "Tukaram Appraisal",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 25.7500,
    longitude: 71.1800,
    data_kind: "synthetic",
    operator: "Cairn Oil & Gas (Synthetic Ref)",
    target_formation: "Dharvi Dungar Shale",
    depth_m: 2150,
    primary_hazard: "Sloughing shale & wellbore instability",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Bedding plane shear failures in overpressured Dharvi Dungar lacustrine shales during wiper trips.",
    lithology: "Dark grey laminated fissile shale with siderite bands",
    spud_year: 2024,
  },
  {
    id: "synth-jsl-05",
    well_id: "JSL-05-MAIN",
    name: "Jaisalmer JSL-05",
    field_name: "Manhera Tibba Gas",
    basin: "Rajasthan (Barmer)",
    basin_key: "rajasthan",
    state: "Rajasthan",
    latitude: 26.9150,
    longitude: 70.9200,
    data_kind: "synthetic",
    operator: "OIL / ONGC (Synthetic Ref)",
    target_formation: "Sanu / Pariwar Sandstone",
    depth_m: 2780,
    primary_hazard: "Depleted reservoir differential sticking",
    event_type: "stuck_pipe",
    event_count: 1,
    incident_summary: "Pressure depletion in mature Sanu gas sand caused 1,200 psi overbalance and drillstring differential sticking.",
    lithology: "Glauconitic calcareous sandstones and sandy shales",
    spud_year: 2021,
  },

  /* ═══════════════════════════════════════════════════════════════
     3. CAMBAY BASIN (GUJARAT) (6 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "synth-ank-12",
    well_id: "ANK-12-MAIN",
    name: "Ankleshwar ANK-12",
    field_name: "Ankleshwar South Block",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 21.6280,
    longitude: 73.0150,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Hazad Member (Ankleshwar Fm)",
    depth_m: 2250,
    primary_hazard: "Differential sticking in depleted multi-layer sands",
    event_type: "stuck_pipe",
    event_count: 1,
    incident_summary: "Differentially stuck at 1,740 m in Hazad Sand-S1 due to pressure drawdown. Freed using ester-based lubricant soak.",
    lithology: "Deltaic quartzose sandstones with sideritic nodules",
    spud_year: 2020,
  },
  {
    id: "synth-gnd-05",
    well_id: "GND-05-MAIN",
    name: "Gandhar GND-05",
    field_name: "Gandhar Giant Field",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 21.8900,
    longitude: 72.8250,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Hazad / Cambay Shale",
    depth_m: 3100,
    primary_hazard: "Gas kick during coring in GS-9 sand",
    event_type: "kick",
    event_count: 2,
    incident_summary: "Drilling break at 2,860 m followed by 22 bbl mud gain; gas cut mud from 1.24 SG down to 0.98 SG. Shut in on BOP.",
    lithology: "Interbedded distributary channel sandstones and thick marine shales",
    spud_year: 2023,
  },
  {
    id: "synth-kll-18",
    well_id: "KLL-18-MAIN",
    name: "Kalol KLL-18",
    field_name: "Kalol North Gujarat",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 23.2350,
    longitude: 72.4950,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Kalol Sertha Member",
    depth_m: 1780,
    primary_hazard: "Coal bed sloughing and drill pipe pack-off",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Cleated Kalol coal seam IX at 1,450 m collapsed into hole during back-reaming; high torque and pack-off cured with PAC mud.",
    lithology: "Thick sub-bituminous coal seams interbedded with carbonaceous shales",
    spud_year: 2022,
  },
  {
    id: "synth-msh-09",
    well_id: "MSH-09-MAIN",
    name: "Mehsana MSH-09",
    field_name: "Mehsana Heavy Oil Belt",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 23.5900,
    longitude: 72.3850,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Mandhali Sandstone",
    depth_m: 1950,
    primary_hazard: "Mud loss in high permeability unconsolidated sand",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "40 bbl lost circulation in loose Mandhali sand at 1,320 m MD. Pumped coarse walnut shell pill.",
    lithology: "Friable coarse sands saturated with viscous heavy oil",
    spud_year: 2021,
  },
  {
    id: "synth-cbd-03",
    well_id: "CBD-03-MAIN",
    name: "Cambay Deep CBD-03",
    field_name: "Cambay Syncline Deep",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 22.3150,
    longitude: 72.6200,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Cambay Shale & Olpad",
    depth_m: 3450,
    primary_hazard: "Abnormal overpressure in thick thermal kitchen shale",
    event_type: "abnormal_pressure",
    event_count: 2,
    incident_summary: "Pore pressure ramped from 1.15 SG equivalent to 1.62 SG in lower Cambay black shale; high gas connection kicks.",
    lithology: "Organic-rich overpressured black siliceous shale",
    spud_year: 2023,
  },
  {
    id: "synth-san-06",
    well_id: "SAN-06-MAIN",
    name: "Sanand SAN-06",
    field_name: "Sanand Field",
    basin: "Cambay",
    basin_key: "cambay",
    state: "Gujarat",
    latitude: 23.0100,
    longitude: 72.3400,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Kalol Formation",
    depth_m: 1680,
    primary_hazard: "Lost circulation in fractured limestone cap",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Loss rate 30 bbl/hr in fractured sandy limestone at 1,180 m; cured with mica flake and sawdust pill.",
    lithology: "Sandy marl and argillaceous limestone",
    spud_year: 2020,
  },

  /* ═══════════════════════════════════════════════════════════════
     4. MUMBAI OFFSHORE BASIN (ARABIAN SEA) (6 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "synth-mhn-01",
    well_id: "MHN-01-MAIN",
    name: "Mumbai High North MHN-01",
    field_name: "Mumbai High Platform N-1",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 19.4167,
    longitude: 71.3500,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "L-III Miocene Limestone",
    depth_m: 1980,
    primary_hazard: "Total lost circulation in cavernous carbonate reef",
    event_type: "mud_loss",
    event_count: 2,
    incident_summary: "Dropped into 1.2 m cavern at 1,450 m MD in L-III reservoir; total fluid loss cured with thixotropic cement plug.",
    lithology: "Bioclastic vuggy limestone with extensive moldic and vuggy porosity",
    spud_year: 2022,
  },
  {
    id: "synth-mhs-04",
    well_id: "MHS-04-MAIN",
    name: "Mumbai High South MHS-04",
    field_name: "Mumbai High Platform S-4",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 19.1833,
    longitude: 71.4167,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "L-III & Basal Sand",
    depth_m: 2050,
    primary_hazard: "Differential sticking across high-permeability depleted zones",
    event_type: "stuck_pipe",
    event_count: 1,
    incident_summary: "High water-cut depleted carbonate layer at 1,420 m caused differential wall sticking; jarred upwards with 80 klb.",
    lithology: "Chalky limestone with micritic matrix",
    spud_year: 2023,
  },
  {
    id: "synth-bsn-02",
    well_id: "BSN-02-MAIN",
    name: "Bassein Gas BSN-02",
    field_name: "Bassein Giant Gas Field",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 19.3333,
    longitude: 72.0833,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Bassein Limestone",
    depth_m: 2400,
    primary_hazard: "High volume sour gas kick (H2S trace)",
    event_type: "kick",
    event_count: 2,
    incident_summary: "Gas kick at 2,240 m MD in top Bassein limestone; 35 bbl pit gain with 15 ppm H2S detected at shaker. Kill mud 1.32 SG.",
    lithology: "Massive foraminiferal grainstone and packstone carbonate",
    spud_year: 2021,
  },
  {
    id: "synth-hra-06",
    well_id: "HRA-06-MAIN",
    name: "Heera HRA-06",
    field_name: "Heera Complex",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 18.8667,
    longitude: 72.2500,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Heera Limestone & Basal Clastic",
    depth_m: 1720,
    primary_hazard: "Tight hole in swelling shale interbeds",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Tight hole in Chinchini shale at 1,150 m during 60-degree deviated drilling; conditioned with KCl polymer mud.",
    lithology: "Thin bedded limestone alternating with grey marine claystones",
    spud_year: 2022,
  },
  {
    id: "synth-nml-03",
    well_id: "NML-03-MAIN",
    name: "Neelam NML-03",
    field_name: "Neelam Field",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 18.7833,
    longitude: 72.3833,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "B-172 & Mukta Carbonates",
    depth_m: 2180,
    primary_hazard: "Mud loss into micro-fractured dolomite",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "50 bbl mud loss in dolomitized section at 1,890 m MD; treated with sized calcium carbonate blend.",
    lithology: "Sucrosic dolomite and calcareous sandstones",
    spud_year: 2024,
  },
  {
    id: "synth-pan-08",
    well_id: "PAN-08-MAIN",
    name: "Panna PAN-08",
    field_name: "Panna-Mukta Sector",
    basin: "Mumbai Offshore",
    basin_key: "mumbai_offshore",
    state: "Offshore (Arabian Sea)",
    latitude: 19.5500,
    longitude: 71.9500,
    data_kind: "synthetic",
    operator: "Joint Venture (Synthetic Ref)",
    target_formation: "Paleocene Basal Clastics & Granite",
    depth_m: 2850,
    primary_hazard: "Abrasive drilling and severe bit bounce in basement",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "Encountered weathered granitic basement at 2,620 m; severe vibration and ring-out of PDC cutters.",
    lithology: "Arkosic conglomerates and fractured granodiorite basement",
    spud_year: 2020,
  },

  /* ═══════════════════════════════════════════════════════════════
     5. KRISHNA-GODAVARI BASIN (KG OFFSHORE & ONSHORE) (5 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "synth-rvw-03",
    well_id: "RVW-03-MAIN",
    name: "Ravva RVW-03",
    field_name: "Ravva Offshore Field",
    basin: "Krishna-Godavari",
    basin_key: "krishna_godavari",
    state: "Andhra Pradesh (Offshore)",
    latitude: 16.4850,
    longitude: 82.3150,
    data_kind: "synthetic",
    operator: "Vedanta / ONGC (Synthetic Ref)",
    target_formation: "Ravva Miocene Sandstone",
    depth_m: 2100,
    primary_hazard: "High volume water cut mud loss",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Lost circulation (42 bbl/hr) in unconsolidated beach barrier bar sands at 1,580 m MD.",
    lithology: "Coarse well-sorted quartzose sandstone with shell fragments",
    spud_year: 2021,
  },
  {
    id: "synth-kgd-06",
    well_id: "KGD-06-MAIN",
    name: "KG-D6 Deepwater KGD-06",
    field_name: "KG-D6 Deepwater Block",
    basin: "Krishna-Godavari",
    basin_key: "krishna_godavari",
    state: "Andhra Pradesh (Deepwater)",
    latitude: 16.2150,
    longitude: 82.5200,
    data_kind: "synthetic",
    operator: "RIL / BP (Synthetic Ref)",
    target_formation: "Pliocene Channel Turbidites",
    depth_m: 3750,
    primary_hazard: "Shallow water flow (SWF) & deep gas kicks",
    event_type: "kick",
    event_count: 2,
    incident_summary: "Water depth 1,200 m; encountered overpressured shallow water sand flow at 1,850 m TVD; gas kick at 3,420 m MD.",
    lithology: "Deep marine canyon-fill turbiditic sandstones enclosed in hemipelagic clays",
    spud_year: 2023,
  },
  {
    id: "synth-amp-08",
    well_id: "AMP-08-MAIN",
    name: "Amalapuram AMP-08",
    field_name: "Amalapuram Onshore High",
    basin: "Krishna-Godavari",
    basin_key: "krishna_godavari",
    state: "Andhra Pradesh",
    latitude: 16.5800,
    longitude: 81.9950,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Pasarlapudi Sandstone",
    depth_m: 2900,
    primary_hazard: "High pressure gas kick & tight hole",
    event_type: "kick",
    event_count: 1,
    incident_summary: "High pressure gas sand encountered at 2,750 m with 28 bbl pit volume gain; closed annular and weighted up to 1.38 SG.",
    lithology: "Distributary mouth bar sandstones with thin coal streaks",
    spud_year: 2022,
  },
  {
    id: "synth-mdn-02",
    well_id: "MDN-02-MAIN",
    name: "Madanapuram MDN-02",
    field_name: "Madanapuram Rift Graben",
    basin: "Krishna-Godavari",
    basin_key: "krishna_godavari",
    state: "Andhra Pradesh",
    latitude: 16.7200,
    longitude: 81.7500,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Raghavapuram Shale",
    depth_m: 3150,
    primary_hazard: "Sloughing shale & drillstring differential sticking",
    event_type: "stuck_pipe",
    event_count: 1,
    incident_summary: "Thick Raghavapuram marine shale heaved into wellbore during connection; pipe stuck and freed with jarring.",
    lithology: "Dark grey pyritic splintery shale with high clay activity",
    spud_year: 2023,
  },
  {
    id: "synth-ngl-01",
    well_id: "NGL-01-MAIN",
    name: "Nagayalanka NGL-01",
    field_name: "Nagayalanka Tight Reservoir",
    basin: "Krishna-Godavari",
    basin_key: "krishna_godavari",
    state: "Andhra Pradesh",
    latitude: 16.0200,
    longitude: 81.0800,
    data_kind: "synthetic",
    operator: "Cairn / ONGC (Synthetic Ref)",
    target_formation: "Gollapalli Sandstone",
    depth_m: 3400,
    primary_hazard: "Abnormal pressure in tight low-perm sand",
    event_type: "abnormal_pressure",
    event_count: 1,
    incident_summary: "Pore pressure equivalent 1.45 SG in tight Early Cretaceous sandstone; high torque and ballooning.",
    lithology: "Hard silica-cemented tight sandstone and conglomeratic beds",
    spud_year: 2020,
  },

  /* ═══════════════════════════════════════════════════════════════
     6. CAUVERY BASIN (TAMIL NADU & PALK BAY) (4 Wells)
     ═══════════════════════════════════════════════════════════════ */
  {
    id: "synth-nrm-02",
    well_id: "NRM-02-MAIN",
    name: "Narimanam NRM-02",
    field_name: "Narimanam Field",
    basin: "Cauvery",
    basin_key: "cauvery",
    state: "Tamil Nadu",
    latitude: 10.8200,
    longitude: 79.7400,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Kamalapuram Formation",
    depth_m: 2350,
    primary_hazard: "Mud loss in fractured limestone & sandstone",
    event_type: "mud_loss",
    event_count: 1,
    incident_summary: "Lost circulation (35 bbl/hr) at 1,980 m MD in Kamalapuram reservoir; cured with fine/medium nutshell LCM.",
    lithology: "Interbedded deltaic sandstones, siltstones, and calcareous marls",
    spud_year: 2021,
  },
  {
    id: "synth-kvk-05",
    well_id: "KVK-05-MAIN",
    name: "Kovilkalappal KVK-05",
    field_name: "Kovilkalappal Structure",
    basin: "Cauvery",
    basin_key: "cauvery",
    state: "Tamil Nadu",
    latitude: 10.6500,
    longitude: 79.5200,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Bhuvanagiri Sandstone",
    depth_m: 2800,
    primary_hazard: "High pressure gas influx during drilling break",
    event_type: "kick",
    event_count: 1,
    incident_summary: "Cretaceous Bhuvanagiri sand at 2,490 m yielded 16 bbl pit gain in 10 minutes. Circulated out with 1.28 SG mud.",
    lithology: "Fine to medium grained glauconitic sandstone",
    spud_year: 2023,
  },
  {
    id: "synth-ady-01",
    well_id: "ADY-01-MAIN",
    name: "Adiyakkamangalam ADY-01",
    field_name: "Nagapattinam Sub-basin",
    basin: "Cauvery",
    basin_key: "cauvery",
    state: "Tamil Nadu",
    latitude: 10.7450,
    longitude: 79.6200,
    data_kind: "synthetic",
    operator: "ONGC (Synthetic Ref)",
    target_formation: "Nannilam Formation",
    depth_m: 2600,
    primary_hazard: "Tight hole and drag in reactive Cretaceous shale",
    event_type: "tight_hole",
    event_count: 1,
    incident_summary: "High overpull observed when pulling out through Nannilam swelling claystones; reamed and increased mud weight.",
    lithology: "Calcareous shale with thin turbiditic siltstone laminations",
    spud_year: 2022,
  },
  {
    id: "synth-py-03",
    well_id: "PY-03-MAIN",
    name: "PY-3 Offshore PY-03",
    field_name: "PY-3 Offshore Field",
    basin: "Cauvery",
    basin_key: "cauvery",
    state: "Tamil Nadu (Offshore)",
    latitude: 11.2350,
    longitude: 79.9100,
    data_kind: "synthetic",
    operator: "Hardy / ONGC (Synthetic Ref)",
    target_formation: "Albian Sandstone",
    depth_m: 3250,
    primary_hazard: "Total lost circulation in fractured Cretaceous sandstone",
    event_type: "mud_loss",
    event_count: 2,
    incident_summary: "Total mud loss at 2,820 m MD into fractured fault block; required 40 bbl gunk plug to regain circulation.",
    lithology: "Feldspathic sandstones with carbonate cementation",
    spud_year: 2020,
  },
];

/**
 * Calculate geodesic distance between two lat/lng coordinates in kilometers (Haversine formula).
 */
export function haversineKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/**
 * Get all synthetic wells matching a basin filter.
 */
export function getSyntheticWellsByBasin(
  basinKey: BasinKey
): SyntheticBasinWell[] {
  if (basinKey === "all") return ALL_SYNTHETIC_WELLS;
  return ALL_SYNTHETIC_WELLS.filter((w) => w.basin_key === basinKey);
}

/**
 * Find nearest synthetic wells to a given point.
 */
export function getNearestSyntheticWells(
  lat: number,
  lng: number,
  limit = 5,
  excludeId?: string
): (SyntheticBasinWell & { distanceKm: number })[] {
  return ALL_SYNTHETIC_WELLS.filter((w) => w.id !== excludeId)
    .map((w) => ({
      ...w,
      distanceKm: haversineKm(lat, lng, w.latitude, w.longitude),
    }))
    .sort((a, b) => a.distanceKm - b.distanceKm)
    .slice(0, limit);
}
